<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PlatformTarget>x64</PlatformTarget>
    <SelfContained>false</SelfContained>
    <RollForward>Major</RollForward>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ManagedBass" Version="3.1.1" />
    <PackageReference Include="ManagedBass.Mix" Version="3.1.1" />
    <PackageReference Include="ManagedBass.Fx" Version="3.1.1" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\Assets\Plugins\BassNative\Windows\x86_64\*.dll"
          CopyToOutputDirectory="PreserveNewest"
          TargetPath="%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
