//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Cysharp.Text;

namespace YARG.Localization
{
    public static partial class Localize
    {
        #region Keys

        public static string MakeKey<T1, T2>(
            T1 t1, T2 t2)
        {
            return ZString.Concat(t1, '.', t2);
        }

        public static string Key<T1, T2>(
            T1 t1, T2 t2)
        {
            return Key(MakeKey(t1, t2));
        }

        public static string MakeKey<T1, T2, T3>(
            T1 t1, T2 t2, T3 t3)
        {
            return ZString.Concat(t1, '.', t2, '.', t3);
        }

        public static string Key<T1, T2, T3>(
            T1 t1, T2 t2, T3 t3)
        {
            return Key(MakeKey(t1, t2, t3));
        }

        public static string MakeKey<T1, T2, T3, T4>(
            T1 t1, T2 t2, T3 t3, T4 t4)
        {
            return ZString.Concat(t1, '.', t2, '.', t3, '.', t4);
        }

        public static string Key<T1, T2, T3, T4>(
            T1 t1, T2 t2, T3 t3, T4 t4)
        {
            return Key(MakeKey(t1, t2, t3, t4));
        }

        #endregion

        #region Format

        public static string KeyFormat<F1>(
            string key, F1 f1)
        {
            return ZString.Format(Key(key), f1);
        }

        public static string KeyFormat<K1, K2, F1>(
            (K1 k1, K2 k2) key, F1 f1)
        {
            return ZString.Format(Key(key.k1, key.k2),
                f1);
        }

        public static string KeyFormat<K1, K2, K3, F1>(
            (K1 k1, K2 k2, K3 k3) key, F1 f1)
        {
            return ZString.Format(Key(key.k1, key.k2, key.k3),
                f1);
        }

        public static string KeyFormat<K1, K2, K3, K4, F1>(
            (K1 k1, K2 k2, K3 k3, K4 k4) key, F1 f1)
        {
            return ZString.Format(Key(key.k1, key.k2, key.k3, key.k4),
                f1);
        }

        public static string KeyFormat<F1, F2>(
            string key, F1 f1, F2 f2)
        {
            return ZString.Format(Key(key), f1, f2);
        }

        public static string KeyFormat<K1, K2, F1, F2>(
            (K1 k1, K2 k2) key, F1 f1, F2 f2)
        {
            return ZString.Format(Key(key.k1, key.k2),
                f1, f2);
        }

        public static string KeyFormat<K1, K2, K3, F1, F2>(
            (K1 k1, K2 k2, K3 k3) key, F1 f1, F2 f2)
        {
            return ZString.Format(Key(key.k1, key.k2, key.k3),
                f1, f2);
        }

        public static string KeyFormat<K1, K2, K3, K4, F1, F2>(
            (K1 k1, K2 k2, K3 k3, K4 k4) key, F1 f1, F2 f2)
        {
            return ZString.Format(Key(key.k1, key.k2, key.k3, key.k4),
                f1, f2);
        }

        public static string KeyFormat<F1, F2, F3>(
            string key, F1 f1, F2 f2, F3 f3)
        {
            return ZString.Format(Key(key), f1, f2, f3);
        }

        public static string KeyFormat<K1, K2, F1, F2, F3>(
            (K1 k1, K2 k2) key, F1 f1, F2 f2, F3 f3)
        {
            return ZString.Format(Key(key.k1, key.k2),
                f1, f2, f3);
        }

        public static string KeyFormat<K1, K2, K3, F1, F2, F3>(
            (K1 k1, K2 k2, K3 k3) key, F1 f1, F2 f2, F3 f3)
        {
            return ZString.Format(Key(key.k1, key.k2, key.k3),
                f1, f2, f3);
        }

        public static string KeyFormat<K1, K2, K3, K4, F1, F2, F3>(
            (K1 k1, K2 k2, K3 k3, K4 k4) key, F1 f1, F2 f2, F3 f3)
        {
            return ZString.Format(Key(key.k1, key.k2, key.k3, key.k4),
                f1, f2, f3);
        }

        public static string KeyFormat<F1, F2, F3, F4>(
            string key, F1 f1, F2 f2, F3 f3, F4 f4)
        {
            return ZString.Format(Key(key), f1, f2, f3, f4);
        }

        public static string KeyFormat<K1, K2, F1, F2, F3, F4>(
            (K1 k1, K2 k2) key, F1 f1, F2 f2, F3 f3, F4 f4)
        {
            return ZString.Format(Key(key.k1, key.k2),
                f1, f2, f3, f4);
        }

        public static string KeyFormat<K1, K2, K3, F1, F2, F3, F4>(
            (K1 k1, K2 k2, K3 k3) key, F1 f1, F2 f2, F3 f3, F4 f4)
        {
            return ZString.Format(Key(key.k1, key.k2, key.k3),
                f1, f2, f3, f4);
        }

        public static string KeyFormat<K1, K2, K3, K4, F1, F2, F3, F4>(
            (K1 k1, K2 k2, K3 k3, K4 k4) key, F1 f1, F2 f2, F3 f3, F4 f4)
        {
            return ZString.Format(Key(key.k1, key.k2, key.k3, key.k4),
                f1, f2, f3, f4);
        }

        public static string KeyFormat<F1, F2, F3, F4, F5>(
            string key, F1 f1, F2 f2, F3 f3, F4 f4, F5 f5)
        {
            return ZString.Format(Key(key), f1, f2, f3, f4, f5);
        }

        public static string KeyFormat<K1, K2, F1, F2, F3, F4, F5>(
            (K1 k1, K2 k2) key, F1 f1, F2 f2, F3 f3, F4 f4, F5 f5)
        {
            return ZString.Format(Key(key.k1, key.k2),
                f1, f2, f3, f4, f5);
        }

        public static string KeyFormat<K1, K2, K3, F1, F2, F3, F4, F5>(
            (K1 k1, K2 k2, K3 k3) key, F1 f1, F2 f2, F3 f3, F4 f4, F5 f5)
        {
            return ZString.Format(Key(key.k1, key.k2, key.k3),
                f1, f2, f3, f4, f5);
        }

        public static string KeyFormat<K1, K2, K3, K4, F1, F2, F3, F4, F5>(
            (K1 k1, K2 k2, K3 k3, K4 k4) key, F1 f1, F2 f2, F3 f3, F4 f4, F5 f5)
        {
            return ZString.Format(Key(key.k1, key.k2, key.k3, key.k4),
                f1, f2, f3, f4, f5);
        }

        public static string KeyFormat<F1, F2, F3, F4, F5, F6>(
            string key, F1 f1, F2 f2, F3 f3, F4 f4, F5 f5, F6 f6)
        {
            return ZString.Format(Key(key), f1, f2, f3, f4, f5, f6);
        }

        public static string KeyFormat<K1, K2, F1, F2, F3, F4, F5, F6>(
            (K1 k1, K2 k2) key, F1 f1, F2 f2, F3 f3, F4 f4, F5 f5, F6 f6)
        {
            return ZString.Format(Key(key.k1, key.k2),
                f1, f2, f3, f4, f5, f6);
        }

        public static string KeyFormat<K1, K2, K3, F1, F2, F3, F4, F5, F6>(
            (K1 k1, K2 k2, K3 k3) key, F1 f1, F2 f2, F3 f3, F4 f4, F5 f5, F6 f6)
        {
            return ZString.Format(Key(key.k1, key.k2, key.k3),
                f1, f2, f3, f4, f5, f6);
        }

        public static string KeyFormat<K1, K2, K3, K4, F1, F2, F3, F4, F5, F6>(
            (K1 k1, K2 k2, K3 k3, K4 k4) key, F1 f1, F2 f2, F3 f3, F4 f4, F5 f5, F6 f6)
        {
            return ZString.Format(Key(key.k1, key.k2, key.k3, key.k4),
                f1, f2, f3, f4, f5, f6);
        }

        public static string KeyFormat<F1, F2, F3, F4, F5, F6, F7>(
            string key, F1 f1, F2 f2, F3 f3, F4 f4, F5 f5, F6 f6, F7 f7)
        {
            return ZString.Format(Key(key), f1, f2, f3, f4, f5, f6, f7);
        }

        public static string KeyFormat<K1, K2, F1, F2, F3, F4, F5, F6, F7>(
            (K1 k1, K2 k2) key, F1 f1, F2 f2, F3 f3, F4 f4, F5 f5, F6 f6, F7 f7)
        {
            return ZString.Format(Key(key.k1, key.k2),
                f1, f2, f3, f4, f5, f6, f7);
        }

        public static string KeyFormat<K1, K2, K3, F1, F2, F3, F4, F5, F6, F7>(
            (K1 k1, K2 k2, K3 k3) key, F1 f1, F2 f2, F3 f3, F4 f4, F5 f5, F6 f6, F7 f7)
        {
            return ZString.Format(Key(key.k1, key.k2, key.k3),
                f1, f2, f3, f4, f5, f6, f7);
        }

        public static string KeyFormat<K1, K2, K3, K4, F1, F2, F3, F4, F5, F6, F7>(
            (K1 k1, K2 k2, K3 k3, K4 k4) key, F1 f1, F2 f2, F3 f3, F4 f4, F5 f5, F6 f6, F7 f7)
        {
            return ZString.Format(Key(key.k1, key.k2, key.k3, key.k4),
                f1, f2, f3, f4, f5, f6, f7);
        }

        public static string KeyFormat<F1, F2, F3, F4, F5, F6, F7, F8>(
            string key, F1 f1, F2 f2, F3 f3, F4 f4, F5 f5, F6 f6, F7 f7, F8 f8)
        {
            return ZString.Format(Key(key), f1, f2, f3, f4, f5, f6, f7, f8);
        }

        public static string KeyFormat<K1, K2, F1, F2, F3, F4, F5, F6, F7, F8>(
            (K1 k1, K2 k2) key, F1 f1, F2 f2, F3 f3, F4 f4, F5 f5, F6 f6, F7 f7, F8 f8)
        {
            return ZString.Format(Key(key.k1, key.k2),
                f1, f2, f3, f4, f5, f6, f7, f8);
        }

        public static string KeyFormat<K1, K2, K3, F1, F2, F3, F4, F5, F6, F7, F8>(
            (K1 k1, K2 k2, K3 k3) key, F1 f1, F2 f2, F3 f3, F4 f4, F5 f5, F6 f6, F7 f7, F8 f8)
        {
            return ZString.Format(Key(key.k1, key.k2, key.k3),
                f1, f2, f3, f4, f5, f6, f7, f8);
        }

        public static string KeyFormat<K1, K2, K3, K4, F1, F2, F3, F4, F5, F6, F7, F8>(
            (K1 k1, K2 k2, K3 k3, K4 k4) key, F1 f1, F2 f2, F3 f3, F4 f4, F5 f5, F6 f6, F7 f7, F8 f8)
        {
            return ZString.Format(Key(key.k1, key.k2, key.k3, key.k4),
                f1, f2, f3, f4, f5, f6, f7, f8);
        }

        public static string KeyFormat<F1, F2, F3, F4, F5, F6, F7, F8, F9>(
            string key, F1 f1, F2 f2, F3 f3, F4 f4, F5 f5, F6 f6, F7 f7, F8 f8, F9 f9)
        {
            return ZString.Format(Key(key), f1, f2, f3, f4, f5, f6, f7, f8, f9);
        }

        public static string KeyFormat<K1, K2, F1, F2, F3, F4, F5, F6, F7, F8, F9>(
            (K1 k1, K2 k2) key, F1 f1, F2 f2, F3 f3, F4 f4, F5 f5, F6 f6, F7 f7, F8 f8, F9 f9)
        {
            return ZString.Format(Key(key.k1, key.k2),
                f1, f2, f3, f4, f5, f6, f7, f8, f9);
        }

        public static string KeyFormat<K1, K2, K3, F1, F2, F3, F4, F5, F6, F7, F8, F9>(
            (K1 k1, K2 k2, K3 k3) key, F1 f1, F2 f2, F3 f3, F4 f4, F5 f5, F6 f6, F7 f7, F8 f8, F9 f9)
        {
            return ZString.Format(Key(key.k1, key.k2, key.k3),
                f1, f2, f3, f4, f5, f6, f7, f8, f9);
        }

        public static string KeyFormat<K1, K2, K3, K4, F1, F2, F3, F4, F5, F6, F7, F8, F9>(
            (K1 k1, K2 k2, K3 k3, K4 k4) key, F1 f1, F2 f2, F3 f3, F4 f4, F5 f5, F6 f6, F7 f7, F8 f8, F9 f9)
        {
            return ZString.Format(Key(key.k1, key.k2, key.k3, key.k4),
                f1, f2, f3, f4, f5, f6, f7, f8, f9);
        }

        public static string KeyFormat<F1, F2, F3, F4, F5, F6, F7, F8, F9, F10>(
            string key, F1 f1, F2 f2, F3 f3, F4 f4, F5 f5, F6 f6, F7 f7, F8 f8, F9 f9, F10 f10)
        {
            return ZString.Format(Key(key), f1, f2, f3, f4, f5, f6, f7, f8, f9, f10);
        }

        public static string KeyFormat<K1, K2, F1, F2, F3, F4, F5, F6, F7, F8, F9, F10>(
            (K1 k1, K2 k2) key, F1 f1, F2 f2, F3 f3, F4 f4, F5 f5, F6 f6, F7 f7, F8 f8, F9 f9, F10 f10)
        {
            return ZString.Format(Key(key.k1, key.k2),
                f1, f2, f3, f4, f5, f6, f7, f8, f9, f10);
        }

        public static string KeyFormat<K1, K2, K3, F1, F2, F3, F4, F5, F6, F7, F8, F9, F10>(
            (K1 k1, K2 k2, K3 k3) key, F1 f1, F2 f2, F3 f3, F4 f4, F5 f5, F6 f6, F7 f7, F8 f8, F9 f9, F10 f10)
        {
            return ZString.Format(Key(key.k1, key.k2, key.k3),
                f1, f2, f3, f4, f5, f6, f7, f8, f9, f10);
        }

        public static string KeyFormat<K1, K2, K3, K4, F1, F2, F3, F4, F5, F6, F7, F8, F9, F10>(
            (K1 k1, K2 k2, K3 k3, K4 k4) key, F1 f1, F2 f2, F3 f3, F4 f4, F5 f5, F6 f6, F7 f7, F8 f8, F9 f9, F10 f10)
        {
            return ZString.Format(Key(key.k1, key.k2, key.k3, key.k4),
                f1, f2, f3, f4, f5, f6, f7, f8, f9, f10);
        }

        #endregion
    }
}