using System.Collections.Generic;
using PlasticBand.Haptics;
using UnityEngine;
using UnityEngine.Experimental.GlobalIllumination;
using UnityEngine.SceneManagement;
using YARG.Core;
using YARG.Core.Chart;
using YARG.Core.Logging;
using YARG.Gameplay;
using YARG.Settings;
using Random = UnityEngine.Random;

namespace YARG.Integration
{
    public class DataStreamGameplayMonitor : GameplayBehaviour
    {
        private readonly struct VocalNoteEvent
        {
            public float Pitch { get; }
            public double StartTime { get; }
            public double EndTime { get; }

            public VocalNoteEvent(float pitch, double startTime, double endTime, bool isActive = false)
            {
                Pitch = pitch;
                StartTime = startTime;
                EndTime = endTime;
            }
        }

        public static VenueTrack Venue { get; private set; }
        public static int LightingIndex { get; private set; }

        private SyncTrack _sync;

        private List<VocalsPhrase> _vocals;
        private List<VocalsPhrase> _harmony0;
        private List<VocalsPhrase> _harmony1;
        private List<VocalsPhrase> _harmony2;
        private InstrumentDifficulty<DrumNote> _drums;
        private InstrumentDifficulty<GuitarNote> _guitar;
        private InstrumentDifficulty<GuitarNote> _bass;
        private InstrumentDifficulty<GuitarNote> _keys;

        // These two are just for the pause state.
        private static bool         _currentFogState = false;
        private static LightingType _currentStrobeState = LightingType.StrobeOff;

        private int _vocalsIndex;
        private int _harmony0Index;
        private int _harmony1Index;
        private int _harmony2Index;
        private int _keysIndex;
        private int _syncIndex;
        private int _bpmIndex;
        private int _drumIndex;
        private int _guitarIndex;
        private int _bassIndex;
        private int _stageIndex;
        private int _performerStartIndex;
        private int _performerEndIndex;
        private int _postProcessingIndex;
        private int _cameraCutIndex;
        private double _fogEndTime;

        private List<VocalNoteEvent> _vocalsNotes;
        private List<VocalNoteEvent> _harmony0Notes;
        private List<VocalNoteEvent> _harmony1Notes;
        private List<VocalNoteEvent> _harmony2Notes;

        protected override void OnChartLoaded(SongChart chart)
        {
            //don't bother doing this if the option is off.
            if (!SettingsManager.Settings.DataStreamEnable.Value){return;}

            DataStreamController.Initializer(SceneManager.GetActiveScene());
            DataStreamController.EnqueueFogState(false);
            DataStreamController.EnqueueStrobeState(LightingType.StrobeOff);
            if (GameManager.IsPractice)
            {
                DataStreamController.EnqueueSceneIndex(DataStreamController.SceneIndexByte.Practice);
            }
            DataStreamController.EnqueuePauseState(DataStreamController.PauseStateType.Unpaused);

            // This should be read from the venue itself eventually, but for now, we'll just randomize it.
            DataStreamController.EnqueueVenueSize((DataStreamController.VenueType)Random.Range(1, 2));
            DataStreamController.EnqueueAutoGenVenueTrack(chart.VenueTrack.AutoGenerated);

            Venue = chart.VenueTrack;
            _sync = chart.SyncTrack;
            _vocals = chart.Vocals.Parts[0].NotePhrases;
            _harmony0 = chart.Harmony.Parts[0].NotePhrases;
            _harmony1 = chart.Harmony.Parts[1].NotePhrases;
            _harmony2 = chart.Harmony.Parts[2].NotePhrases;

            _drums = chart.ProDrums.GetDifficulty(Difficulty.Expert);
            _guitar = chart.FiveFretGuitar.GetDifficulty(Difficulty.Expert);
            _bass = chart.FiveFretBass.GetDifficulty(Difficulty.Expert);
            _keys = chart.Keys.GetDifficulty(Difficulty.Expert);

            // Reset the indexes on song restart
            _stageIndex = 0;
            LightingIndex = 0;
            _syncIndex = 0;
            _vocalsIndex = 0;
            _guitarIndex = 0;
            _bassIndex = 0;
            _drumIndex = 0;
            _performerStartIndex = 0;
            _performerEndIndex = 0;
            _postProcessingIndex = 0;
            _keysIndex = 0;
            _cameraCutIndex = 0;
            _fogEndTime = 0;
            DataStreamController.MLCFogRemainingCentiseconds = 0;

            _vocalsNotes = GetAllNoteEvents(_vocals);
            _harmony0Notes = GetAllNoteEvents(_harmony0);
            _harmony1Notes = GetAllNoteEvents(_harmony1);
            _harmony2Notes = GetAllNoteEvents(_harmony2);
        }

        private int GuitarBassKeyboardEventChecker(InstrumentDifficulty<GuitarNote> instrument, ref int instrumentIndex)
        {
            int fretsPressed = 0;

            // Check if the index is within bounds
            if (instrumentIndex >= instrument.Notes.Count)
            {
                return 0; // No notes to process
            }

            var currentNote = instrument.Notes[instrumentIndex];

            // Handle sustained notes
            if (currentNote.Time < currentNote.TimeEnd && currentNote.TimeEnd <= GameManager.SongTime)
            {
                instrumentIndex++;
                return 0; // Sustain note has ended
            }

            // Handle instant notes
            if (!(currentNote.Time <= GameManager.SongTime)) return 0; // No notes currently active
            foreach (var note in currentNote.AllNotes)
            {
                fretsPressed |= (1 << note.Fret);
            }

            if (currentNote.Time == currentNote.TimeEnd)
            {
                // Note is instant, so it is done.
                instrumentIndex++;
            }

            return fretsPressed; // Return instant notes pressed
        }

        private int DrumsEventChecker(InstrumentDifficulty<DrumNote> instrument, ref int instrumentIndex)
        {
            int fretsPressed = 0;

            // Check if the index is within bounds
            if (instrumentIndex >= instrument.Notes.Count)
            {
                return 0; // No notes to process
            }

            var currentNote = instrument.Notes[instrumentIndex];

            // Handle sustained notes
            if (currentNote.Time < currentNote.TimeEnd && currentNote.TimeEnd <= GameManager.SongTime)
            {
                instrumentIndex++;
                return 0; // Sustain note has ended
            }

            // Handle instant notes
            if (!(currentNote.Time <= GameManager.SongTime)) return 0; // No notes currently active

            foreach (var note in currentNote.AllNotes)
            {
                fretsPressed |= (1 << note.Pad);
            }

            if (currentNote.Time == currentNote.TimeEnd)
            {
                // Note is instant
                instrumentIndex++;
            }

            return fretsPressed; // Return notes for sustain
        }

        private float VocalEventChecker(List<VocalNoteEvent> list, ref int listIndex)
        {
            if (listIndex < list.Count && list[listIndex].EndTime <= GameManager.SongTime)
            {
                listIndex++;
                return 0; // Note has ended
            }

            if (listIndex < list.Count && list[listIndex].StartTime <= GameManager.SongTime)
            {
                return list[listIndex].Pitch; // new note starting
            }

            return -2; // don't change the current note
        }


        private void PerformerEventChecker(PerformerEventType type, ref Performer MLCvar)
        {

            // Add all starting performers at or before SongTime
            while (_performerStartIndex < Venue.Performer.Count &&
                Venue.Performer[_performerStartIndex].Time <= GameManager.SongTime &&
                Venue.Performer[_performerStartIndex].Type == type)
            {
                MLCvar |= Venue.Performer[_performerStartIndex].Performers; // use bitwise OR to combine
                QueuePerformerState(type, MLCvar);
                _performerStartIndex++;
            }

            // Remove all ending performers at or before SongTime
            while (_performerEndIndex < Venue.Performer.Count &&
                Venue.Performer[_performerEndIndex].TimeEnd <= GameManager.SongTime &&
                Venue.Performer[_performerEndIndex].Type == type)
            {
                MLCvar &= ~Venue.Performer[_performerEndIndex].Performers; // bitwise remove
                QueuePerformerState(type, MLCvar);
                _performerEndIndex++;
            }
        }

        private static void QueuePerformerState(PerformerEventType type, Performer performers)
        {
            if (type == PerformerEventType.Singalong)
            {
                DataStreamController.EnqueueSingalong(performers);
            }
            else if (type == PerformerEventType.Spotlight)
            {
                DataStreamController.EnqueueSpotlight(performers);
            }
        }

        private void Update()
        {
            // Don't do any of this if the option is off
            if (!SettingsManager.Settings.DataStreamEnable.Value)
            {
                return;
            }

            // Let's get the current state of the game
            // star power
            DataStreamController.UpdatePlayerStarPowerSnapshot(GameManager.Players);

            // Pause state
            //this is uglier than a simple != because the pause state type has 3 states. AtMenu, pause, unpaused.
            switch (DataStreamController.MLCPaused, GameManager.Paused)
            {
                case (DataStreamController.PauseStateType.Unpaused, true):
                    DataStreamController.EnqueuePauseState(DataStreamController.PauseStateType.Paused);

                    // Save current states
                    _currentStrobeState = DataStreamController.MLCStrobeState;
                    _currentFogState = DataStreamController.MLCFogState;

                    // Kill the fog and strobes
                    DataStreamController.EnqueueStrobeState(LightingType.StrobeOff);
                    DataStreamController.EnqueueFogState(false);
                    break;

                case (DataStreamController.PauseStateType.Paused, false):
                    DataStreamController.EnqueuePauseState(DataStreamController.PauseStateType.Unpaused);

                    // Restore previous states
                    DataStreamController.EnqueueStrobeState(_currentStrobeState);
                    DataStreamController.EnqueueFogState(_currentFogState);
                    break;
            }

            // Instrument events - enqueue to prevent missed notes between timer ticks
            var drums = DrumsEventChecker(_drums, ref _drumIndex);
            var guitar = GuitarBassKeyboardEventChecker(_guitar, ref _guitarIndex);
            var bass = GuitarBassKeyboardEventChecker(_bass, ref _bassIndex);
            var keys = GuitarBassKeyboardEventChecker(_keys, ref _keysIndex);
            DataStreamController.EnqueueInstrumentNotes(drums, guitar, bass, keys);

            // Vocal events
            var vocalNote = VocalEventChecker(_vocalsNotes, ref _vocalsIndex);
            if (vocalNote != -2)
            {
                DataStreamController.MLCCurrentVocalNote = vocalNote;
            }

            var harmony0Note = VocalEventChecker(_harmony0Notes, ref _harmony0Index);
            if (harmony0Note != -2)
            {
                DataStreamController.MLCCurrentHarmony0Note = harmony0Note;
            }

            var harmony1Note = VocalEventChecker(_harmony1Notes, ref _harmony1Index);
            if (harmony1Note != -2)
            {
                DataStreamController.MLCCurrentHarmony1Note = harmony1Note;
            }

            var harmony2Note = VocalEventChecker(_harmony2Notes, ref _harmony2Index);
            if (harmony2Note != -2)
            {
                DataStreamController.MLCCurrentHarmony2Note = harmony2Note;
            }


            //Performer events broken down into two types. Spotlight and Singalong
            PerformerEventChecker(PerformerEventType.Singalong, ref DataStreamController.MLCSingalong);
            PerformerEventChecker(PerformerEventType.Spotlight, ref DataStreamController.MLCSpotlight);


            // Post-processing events
            while (_postProcessingIndex < Venue.PostProcessing.Count &&
                Venue.PostProcessing[_postProcessingIndex].Time <= GameManager.SongTime)
            {
                DataStreamController.EnqueuePostProcessing(Venue.PostProcessing[_postProcessingIndex].Type);
                _postProcessingIndex++;
            }

            // Camera cut events
            while (_cameraCutIndex < Venue.CameraCuts.Count && Venue.CameraCuts[_cameraCutIndex].Time <= GameManager.SongTime)
            {
                DataStreamController.EnqueueCameraCutState(Venue.CameraCuts[_cameraCutIndex].Constraint,
                    Venue.CameraCuts[_cameraCutIndex].Priority, Venue.CameraCuts[_cameraCutIndex].Subject);
                _cameraCutIndex++;
            }

            // Beat line events
            while (_syncIndex < _sync.Beatlines.Count && _sync.Beatlines[_syncIndex].Time <= GameManager.SongTime)
            {
                DataStreamController.EnqueueBeat((byte)_sync.Beatlines[_syncIndex].Type);
                _syncIndex++;
            }

            while (_bpmIndex < _sync.Tempos.Count && _sync.Tempos[_bpmIndex].Time <= GameManager.SongTime)
            {
                //bpm is a double, but sending that in the data stream is unneeded at this point.
                DataStreamController.MLCCurrentBPM = Mathf.Round((float)_sync.Tempos[_bpmIndex].BeatsPerMinute);
                _bpmIndex++;
            }

            // The lighting cues from the venue track are handled here.
            while (LightingIndex < Venue.Lighting.Count && Venue.Lighting[LightingIndex].Time <= GameManager.SongTime)
            {
                switch (Venue.Lighting[LightingIndex].Type)
                {
                    case LightingType.StrobeOff:
                        DataStreamController.EnqueueStrobeState(LightingType.StrobeOff);
                        break;

                    case LightingType.StrobeFast:
                        DataStreamController.EnqueueStrobeState(LightingType.StrobeFast);
                        break;

                    case LightingType.StrobeMedium:
                        DataStreamController.EnqueueStrobeState(LightingType.StrobeMedium);
                        break;

                    case LightingType.StrobeSlow:
                        DataStreamController.EnqueueStrobeState(LightingType.StrobeSlow);
                        break;

                    case LightingType.StrobeFastest:
                        DataStreamController.EnqueueStrobeState(LightingType.StrobeFastest);
                        break;

                    default:
                        // Okay so this a bit odd. The stage kit never has the strobe on with a lighting cue.
                        // But the Strobe_Off event is almost never used, relying instead on the cue change to turn it off.
                        // So this technically should be in the stage kit lighting controller code, but I don't want the
                        // stage kit reaching into this main lighting controller. So we'll just turn it off here.
                        DataStreamController.EnqueueStrobeState(LightingType.StrobeOff);
                        DataStreamController.CurrentLightingCue = Venue.Lighting[LightingIndex];
                        break;
                }

                LightingIndex++;
            }

            // For "fogOn", "fogOff", and "BonusFx" events
            while (_stageIndex < Venue.Stage.Count && Venue.Stage[_stageIndex].Time <= GameManager.SongTime)
            {
                if (Venue.Stage[_stageIndex].Effect == StageEffect.FogOn)
                {
                    DataStreamController.EnqueueFogState(true);
                    _fogEndTime = FindNextFogStopTime(_stageIndex + 1, Venue.Stage[_stageIndex].Time);
                }
                else if (Venue.Stage[_stageIndex].Effect == StageEffect.FogOff)
                {
                    DataStreamController.EnqueueFogState(false);
                    _fogEndTime = 0;
                    DataStreamController.MLCFogRemainingCentiseconds = 0;
                }
                else if (Venue.Stage[_stageIndex].Effect == StageEffect.BonusFx)
                {
                    DataStreamController.EnqueueBonusEffect();
                }

                _stageIndex++;
            }

            UpdateFogRemainingCentiseconds();
        }

        private double FindNextFogStopTime(int stageStartIndex, double fogStartTime)
        {
            var fogEndTime = double.PositiveInfinity;

            for (int i = stageStartIndex; i < Venue.Stage.Count; i++)
            {
                if (Venue.Stage[i].Effect == StageEffect.FogOff)
                {
                    fogEndTime = Venue.Stage[i].Time;
                    break;
                }
            }

            for (int i = 0; i < Venue.Lighting.Count; i++)
            {
                var lighting = Venue.Lighting[i];
                if (lighting.Time <= fogStartTime || !IsFogStopLightingEvent(lighting.Type))
                {
                    continue;
                }

                return lighting.Time < fogEndTime ? lighting.Time : fogEndTime;
            }

            return fogEndTime;
        }

        private static bool IsFogStopLightingEvent(LightingType type)
        {
            return type is not (LightingType.KeyframeNext or LightingType.KeyframePrevious or LightingType.KeyframeFirst
                or LightingType.Verse or LightingType.Chorus);
        }

        private void UpdateFogRemainingCentiseconds()
        {
            if (!DataStreamController.MLCFogState)
            {
                DataStreamController.MLCFogRemainingCentiseconds = 0;
                return;
            }

            var remainingSeconds = _fogEndTime - GameManager.SongTime;
            if (double.IsNaN(remainingSeconds) || remainingSeconds <= 0)
            {
                DataStreamController.EnqueueFogState(false);
                DataStreamController.MLCFogRemainingCentiseconds = 0;
                _fogEndTime = 0;
                return;
            }

            if (double.IsPositiveInfinity(remainingSeconds) || remainingSeconds * 100 >= ushort.MaxValue)
            {
                DataStreamController.MLCFogRemainingCentiseconds = ushort.MaxValue;
                return;
            }

            DataStreamController.MLCFogRemainingCentiseconds =
                (ushort) Mathf.CeilToInt((float) remainingSeconds * 100f);
        }

        private List<VocalNoteEvent> GetAllNoteEvents(List<VocalsPhrase> vocalPhrases)
        {
            var allNoteEvents = new List<VocalNoteEvent>();

            foreach (var phrase in vocalPhrases)
            {
                foreach (var childNote in phrase.PhraseParentNote.ChildNotes)
                {
                    allNoteEvents.Add(new VocalNoteEvent(childNote.Pitch, childNote.Time, childNote.TimeEnd));

                    foreach (var grandChildNote in childNote.ChildNotes)
                    {
                        allNoteEvents.Add(new VocalNoteEvent(grandChildNote.Pitch, grandChildNote.Time,
                            grandChildNote.TimeEnd));
                    }
                }
            }

            // Sort events by time to ensure the correct order
            allNoteEvents.Sort((a, b) => a.StartTime.CompareTo(b.StartTime));
            return allNoteEvents;
        }
    }
}
