using System.Runtime.InteropServices;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Layouts;
using UnityEngine.InputSystem.LowLevel;
using UnityEngine.InputSystem.Utilities;

namespace Minis
{
    /// <summary>
    /// The state format used for a MIDI device.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct MidiDeviceState : IInputStateTypeInfo
    {
        public static readonly FourCC Format = new FourCC('M', 'I', 'D', 'J');
        public FourCC format => Format;

        public const uint NoteOffset = 0;
        public const uint ControlOffset = NoteOffset + 128;
        public const uint PitchBendOffset = ControlOffset + 128;

        [InputControl(name = "note000", displayName = "Note 000 (C-1)",  shortDisplayName = "C-1",  layout = "MidiNote", offset = 0)]
        [InputControl(name = "note001", displayName = "Note 001 (C#-1)", shortDisplayName = "C#-1", layout = "MidiNote", offset = 1)]
        [InputControl(name = "note002", displayName = "Note 002 (D-1)",  shortDisplayName = "D-1",  layout = "MidiNote", offset = 2)]
        [InputControl(name = "note003", displayName = "Note 003 (D#-1)", shortDisplayName = "D#-1", layout = "MidiNote", offset = 3)]
        [InputControl(name = "note004", displayName = "Note 004 (E-1)",  shortDisplayName = "E-1",  layout = "MidiNote", offset = 4)]
        [InputControl(name = "note005", displayName = "Note 005 (F-1)",  shortDisplayName = "F-1",  layout = "MidiNote", offset = 5)]
        [InputControl(name = "note006", displayName = "Note 006 (F#-1)", shortDisplayName = "F#-1", layout = "MidiNote", offset = 6)]
        [InputControl(name = "note007", displayName = "Note 007 (G-1)",  shortDisplayName = "G-1",  layout = "MidiNote", offset = 7)]
        [InputControl(name = "note008", displayName = "Note 008 (G#-1)", shortDisplayName = "G#-1", layout = "MidiNote", offset = 8)]
        [InputControl(name = "note009", displayName = "Note 009 (A-1)",  shortDisplayName = "A-1",  layout = "MidiNote", offset = 9)]
        [InputControl(name = "note010", displayName = "Note 010 (A#-1)", shortDisplayName = "A#-1", layout = "MidiNote", offset = 10)]
        [InputControl(name = "note011", displayName = "Note 011 (B-1)",  shortDisplayName = "B-1",  layout = "MidiNote", offset = 11)]
        [InputControl(name = "note012", displayName = "Note 012 (C0)",   shortDisplayName = "C0",   layout = "MidiNote", offset = 12)]
        [InputControl(name = "note013", displayName = "Note 013 (C#0)",  shortDisplayName = "C#0",  layout = "MidiNote", offset = 13)]
        [InputControl(name = "note014", displayName = "Note 014 (D0)",   shortDisplayName = "D0",   layout = "MidiNote", offset = 14)]
        [InputControl(name = "note015", displayName = "Note 015 (D#0)",  shortDisplayName = "D#0",  layout = "MidiNote", offset = 15)]
        [InputControl(name = "note016", displayName = "Note 016 (E0)",   shortDisplayName = "E0",   layout = "MidiNote", offset = 16)]
        [InputControl(name = "note017", displayName = "Note 017 (F0)",   shortDisplayName = "F0",   layout = "MidiNote", offset = 17)]
        [InputControl(name = "note018", displayName = "Note 018 (F#0)",  shortDisplayName = "F#0",  layout = "MidiNote", offset = 18)]
        [InputControl(name = "note019", displayName = "Note 019 (G0)",   shortDisplayName = "G0",   layout = "MidiNote", offset = 19)]
        [InputControl(name = "note020", displayName = "Note 020 (G#0)",  shortDisplayName = "G#0",  layout = "MidiNote", offset = 20)]
        [InputControl(name = "note021", displayName = "Note 021 (A0)",   shortDisplayName = "A0",   layout = "MidiNote", offset = 21)]
        [InputControl(name = "note022", displayName = "Note 022 (A#0)",  shortDisplayName = "A#0",  layout = "MidiNote", offset = 22)]
        [InputControl(name = "note023", displayName = "Note 023 (B0)",   shortDisplayName = "B0",   layout = "MidiNote", offset = 23)]
        [InputControl(name = "note024", displayName = "Note 024 (C1)",   shortDisplayName = "C1",   layout = "MidiNote", offset = 24)]
        [InputControl(name = "note025", displayName = "Note 025 (C#1)",  shortDisplayName = "C#1",  layout = "MidiNote", offset = 25)]
        [InputControl(name = "note026", displayName = "Note 026 (D1)",   shortDisplayName = "D1",   layout = "MidiNote", offset = 26)]
        [InputControl(name = "note027", displayName = "Note 027 (D#1)",  shortDisplayName = "D#1",  layout = "MidiNote", offset = 27)]
        [InputControl(name = "note028", displayName = "Note 028 (E1)",   shortDisplayName = "E1",   layout = "MidiNote", offset = 28)]
        [InputControl(name = "note029", displayName = "Note 029 (F1)",   shortDisplayName = "F1",   layout = "MidiNote", offset = 29)]
        [InputControl(name = "note030", displayName = "Note 030 (F#1)",  shortDisplayName = "F#1",  layout = "MidiNote", offset = 30)]
        [InputControl(name = "note031", displayName = "Note 031 (G1)",   shortDisplayName = "G1",   layout = "MidiNote", offset = 31)]
        [InputControl(name = "note032", displayName = "Note 032 (G#1)",  shortDisplayName = "G#1",  layout = "MidiNote", offset = 32)]
        [InputControl(name = "note033", displayName = "Note 033 (A1)",   shortDisplayName = "A1",   layout = "MidiNote", offset = 33)]
        [InputControl(name = "note034", displayName = "Note 034 (A#1)",  shortDisplayName = "A#1",  layout = "MidiNote", offset = 34)]
        [InputControl(name = "note035", displayName = "Note 035 (B1)",   shortDisplayName = "B1",   layout = "MidiNote", offset = 35)]
        [InputControl(name = "note036", displayName = "Note 036 (C2)",   shortDisplayName = "C2",   layout = "MidiNote", offset = 36)]
        [InputControl(name = "note037", displayName = "Note 037 (C#2)",  shortDisplayName = "C#2",  layout = "MidiNote", offset = 37)]
        [InputControl(name = "note038", displayName = "Note 038 (D2)",   shortDisplayName = "D2",   layout = "MidiNote", offset = 38)]
        [InputControl(name = "note039", displayName = "Note 039 (D#2)",  shortDisplayName = "D#2",  layout = "MidiNote", offset = 39)]
        [InputControl(name = "note040", displayName = "Note 040 (E2)",   shortDisplayName = "E2",   layout = "MidiNote", offset = 40)]
        [InputControl(name = "note041", displayName = "Note 041 (F2)",   shortDisplayName = "F2",   layout = "MidiNote", offset = 41)]
        [InputControl(name = "note042", displayName = "Note 042 (F#2)",  shortDisplayName = "F#2",  layout = "MidiNote", offset = 42)]
        [InputControl(name = "note043", displayName = "Note 043 (G2)",   shortDisplayName = "G2",   layout = "MidiNote", offset = 43)]
        [InputControl(name = "note044", displayName = "Note 044 (G#2)",  shortDisplayName = "G#2",  layout = "MidiNote", offset = 44)]
        [InputControl(name = "note045", displayName = "Note 045 (A2)",   shortDisplayName = "A2",   layout = "MidiNote", offset = 45)]
        [InputControl(name = "note046", displayName = "Note 046 (A#2)",  shortDisplayName = "A#2",  layout = "MidiNote", offset = 46)]
        [InputControl(name = "note047", displayName = "Note 047 (B2)",   shortDisplayName = "B2",   layout = "MidiNote", offset = 47)]
        [InputControl(name = "note048", displayName = "Note 048 (C3)",   shortDisplayName = "C3",   layout = "MidiNote", offset = 48)]
        [InputControl(name = "note049", displayName = "Note 049 (C#3)",  shortDisplayName = "C#3",  layout = "MidiNote", offset = 49)]
        [InputControl(name = "note050", displayName = "Note 050 (D3)",   shortDisplayName = "D3",   layout = "MidiNote", offset = 50)]
        [InputControl(name = "note051", displayName = "Note 051 (D#3)",  shortDisplayName = "D#3",  layout = "MidiNote", offset = 51)]
        [InputControl(name = "note052", displayName = "Note 052 (E3)",   shortDisplayName = "E3",   layout = "MidiNote", offset = 52)]
        [InputControl(name = "note053", displayName = "Note 053 (F3)",   shortDisplayName = "F3",   layout = "MidiNote", offset = 53)]
        [InputControl(name = "note054", displayName = "Note 054 (F#3)",  shortDisplayName = "F#3",  layout = "MidiNote", offset = 54)]
        [InputControl(name = "note055", displayName = "Note 055 (G3)",   shortDisplayName = "G3",   layout = "MidiNote", offset = 55)]
        [InputControl(name = "note056", displayName = "Note 056 (G#3)",  shortDisplayName = "G#3",  layout = "MidiNote", offset = 56)]
        [InputControl(name = "note057", displayName = "Note 057 (A3)",   shortDisplayName = "A3",   layout = "MidiNote", offset = 57)]
        [InputControl(name = "note058", displayName = "Note 058 (A#3)",  shortDisplayName = "A#3",  layout = "MidiNote", offset = 58)]
        [InputControl(name = "note059", displayName = "Note 059 (B3)",   shortDisplayName = "B3",   layout = "MidiNote", offset = 59)]
        [InputControl(name = "note060", displayName = "Note 060 (C4)",   shortDisplayName = "C4",   layout = "MidiNote", offset = 60)]
        [InputControl(name = "note061", displayName = "Note 061 (C#4)",  shortDisplayName = "C#4",  layout = "MidiNote", offset = 61)]
        [InputControl(name = "note062", displayName = "Note 062 (D4)",   shortDisplayName = "D4",   layout = "MidiNote", offset = 62)]
        [InputControl(name = "note063", displayName = "Note 063 (D#4)",  shortDisplayName = "D#4",  layout = "MidiNote", offset = 63)]
        [InputControl(name = "note064", displayName = "Note 064 (E4)",   shortDisplayName = "E4",   layout = "MidiNote", offset = 64)]
        [InputControl(name = "note065", displayName = "Note 065 (F4)",   shortDisplayName = "F4",   layout = "MidiNote", offset = 65)]
        [InputControl(name = "note066", displayName = "Note 066 (F#4)",  shortDisplayName = "F#4",  layout = "MidiNote", offset = 66)]
        [InputControl(name = "note067", displayName = "Note 067 (G4)",   shortDisplayName = "G4",   layout = "MidiNote", offset = 67)]
        [InputControl(name = "note068", displayName = "Note 068 (G#4)",  shortDisplayName = "G#4",  layout = "MidiNote", offset = 68)]
        [InputControl(name = "note069", displayName = "Note 069 (A4)",   shortDisplayName = "A4",   layout = "MidiNote", offset = 69)]
        [InputControl(name = "note070", displayName = "Note 070 (A#4)",  shortDisplayName = "A#4",  layout = "MidiNote", offset = 70)]
        [InputControl(name = "note071", displayName = "Note 071 (B4)",   shortDisplayName = "B4",   layout = "MidiNote", offset = 71)]
        [InputControl(name = "note072", displayName = "Note 072 (C5)",   shortDisplayName = "C5",   layout = "MidiNote", offset = 72)]
        [InputControl(name = "note073", displayName = "Note 073 (C#5)",  shortDisplayName = "C#5",  layout = "MidiNote", offset = 73)]
        [InputControl(name = "note074", displayName = "Note 074 (D5)",   shortDisplayName = "D5",   layout = "MidiNote", offset = 74)]
        [InputControl(name = "note075", displayName = "Note 075 (D#5)",  shortDisplayName = "D#5",  layout = "MidiNote", offset = 75)]
        [InputControl(name = "note076", displayName = "Note 076 (E5)",   shortDisplayName = "E5",   layout = "MidiNote", offset = 76)]
        [InputControl(name = "note077", displayName = "Note 077 (F5)",   shortDisplayName = "F5",   layout = "MidiNote", offset = 77)]
        [InputControl(name = "note078", displayName = "Note 078 (F#5)",  shortDisplayName = "F#5",  layout = "MidiNote", offset = 78)]
        [InputControl(name = "note079", displayName = "Note 079 (G5)",   shortDisplayName = "G5",   layout = "MidiNote", offset = 79)]
        [InputControl(name = "note080", displayName = "Note 080 (G#5)",  shortDisplayName = "G#5",  layout = "MidiNote", offset = 80)]
        [InputControl(name = "note081", displayName = "Note 081 (A5)",   shortDisplayName = "A5",   layout = "MidiNote", offset = 81)]
        [InputControl(name = "note082", displayName = "Note 082 (A#5)",  shortDisplayName = "A#5",  layout = "MidiNote", offset = 82)]
        [InputControl(name = "note083", displayName = "Note 083 (B5)",   shortDisplayName = "B5",   layout = "MidiNote", offset = 83)]
        [InputControl(name = "note084", displayName = "Note 084 (C6)",   shortDisplayName = "C6",   layout = "MidiNote", offset = 84)]
        [InputControl(name = "note085", displayName = "Note 085 (C#6)",  shortDisplayName = "C#6",  layout = "MidiNote", offset = 85)]
        [InputControl(name = "note086", displayName = "Note 086 (D6)",   shortDisplayName = "D6",   layout = "MidiNote", offset = 86)]
        [InputControl(name = "note087", displayName = "Note 087 (D#6)",  shortDisplayName = "D#6",  layout = "MidiNote", offset = 87)]
        [InputControl(name = "note088", displayName = "Note 088 (E6)",   shortDisplayName = "E6",   layout = "MidiNote", offset = 88)]
        [InputControl(name = "note089", displayName = "Note 089 (F6)",   shortDisplayName = "F6",   layout = "MidiNote", offset = 89)]
        [InputControl(name = "note090", displayName = "Note 090 (F#6)",  shortDisplayName = "F#6",  layout = "MidiNote", offset = 90)]
        [InputControl(name = "note091", displayName = "Note 091 (G6)",   shortDisplayName = "G6",   layout = "MidiNote", offset = 91)]
        [InputControl(name = "note092", displayName = "Note 092 (G#6)",  shortDisplayName = "G#6",  layout = "MidiNote", offset = 92)]
        [InputControl(name = "note093", displayName = "Note 093 (A6)",   shortDisplayName = "A6",   layout = "MidiNote", offset = 93)]
        [InputControl(name = "note094", displayName = "Note 094 (A#6)",  shortDisplayName = "A#6",  layout = "MidiNote", offset = 94)]
        [InputControl(name = "note095", displayName = "Note 095 (B6)",   shortDisplayName = "B6",   layout = "MidiNote", offset = 95)]
        [InputControl(name = "note096", displayName = "Note 096 (C7)",   shortDisplayName = "C7",   layout = "MidiNote", offset = 96)]
        [InputControl(name = "note097", displayName = "Note 097 (C#7)",  shortDisplayName = "C#7",  layout = "MidiNote", offset = 97)]
        [InputControl(name = "note098", displayName = "Note 098 (D7)",   shortDisplayName = "D7",   layout = "MidiNote", offset = 98)]
        [InputControl(name = "note099", displayName = "Note 099 (D#7)",  shortDisplayName = "D#7",  layout = "MidiNote", offset = 99)]
        [InputControl(name = "note100", displayName = "Note 100 (E7)",   shortDisplayName = "E7",   layout = "MidiNote", offset = 100)]
        [InputControl(name = "note101", displayName = "Note 101 (F7)",   shortDisplayName = "F7",   layout = "MidiNote", offset = 101)]
        [InputControl(name = "note102", displayName = "Note 102 (F#7)",  shortDisplayName = "F#7",  layout = "MidiNote", offset = 102)]
        [InputControl(name = "note103", displayName = "Note 103 (G7)",   shortDisplayName = "G7",   layout = "MidiNote", offset = 103)]
        [InputControl(name = "note104", displayName = "Note 104 (G#7)",  shortDisplayName = "G#7",  layout = "MidiNote", offset = 104)]
        [InputControl(name = "note105", displayName = "Note 105 (A7)",   shortDisplayName = "A7",   layout = "MidiNote", offset = 105)]
        [InputControl(name = "note106", displayName = "Note 106 (A#7)",  shortDisplayName = "A#7",  layout = "MidiNote", offset = 106)]
        [InputControl(name = "note107", displayName = "Note 107 (B7)",   shortDisplayName = "B7",   layout = "MidiNote", offset = 107)]
        [InputControl(name = "note108", displayName = "Note 108 (C8)",   shortDisplayName = "C8",   layout = "MidiNote", offset = 108)]
        [InputControl(name = "note109", displayName = "Note 109 (C#8)",  shortDisplayName = "C#8",  layout = "MidiNote", offset = 109)]
        [InputControl(name = "note110", displayName = "Note 110 (D8)",   shortDisplayName = "D8",   layout = "MidiNote", offset = 110)]
        [InputControl(name = "note111", displayName = "Note 111 (D#8)",  shortDisplayName = "D#8",  layout = "MidiNote", offset = 111)]
        [InputControl(name = "note112", displayName = "Note 112 (E8)",   shortDisplayName = "E8",   layout = "MidiNote", offset = 112)]
        [InputControl(name = "note113", displayName = "Note 113 (F8)",   shortDisplayName = "F8",   layout = "MidiNote", offset = 113)]
        [InputControl(name = "note114", displayName = "Note 114 (F#8)",  shortDisplayName = "F#8",  layout = "MidiNote", offset = 114)]
        [InputControl(name = "note115", displayName = "Note 115 (G8)",   shortDisplayName = "G8",   layout = "MidiNote", offset = 115)]
        [InputControl(name = "note116", displayName = "Note 116 (G#8)",  shortDisplayName = "G#8",  layout = "MidiNote", offset = 116)]
        [InputControl(name = "note117", displayName = "Note 117 (A8)",   shortDisplayName = "A8",   layout = "MidiNote", offset = 117)]
        [InputControl(name = "note118", displayName = "Note 118 (A#8)",  shortDisplayName = "A#8",  layout = "MidiNote", offset = 118)]
        [InputControl(name = "note119", displayName = "Note 119 (B8)",   shortDisplayName = "B8",   layout = "MidiNote", offset = 119)]
        [InputControl(name = "note120", displayName = "Note 120 (C9)",   shortDisplayName = "C9",   layout = "MidiNote", offset = 120)]
        [InputControl(name = "note121", displayName = "Note 121 (C#9)",  shortDisplayName = "C#9",  layout = "MidiNote", offset = 121)]
        [InputControl(name = "note122", displayName = "Note 122 (D9)",   shortDisplayName = "D9",   layout = "MidiNote", offset = 122)]
        [InputControl(name = "note123", displayName = "Note 123 (D#9)",  shortDisplayName = "D#9",  layout = "MidiNote", offset = 123)]
        [InputControl(name = "note124", displayName = "Note 124 (E9)",   shortDisplayName = "E9",   layout = "MidiNote", offset = 124)]
        [InputControl(name = "note125", displayName = "Note 125 (F9)",   shortDisplayName = "F9",   layout = "MidiNote", offset = 125)]
        [InputControl(name = "note126", displayName = "Note 126 (F#9)",  shortDisplayName = "F#9",  layout = "MidiNote", offset = 126)]
        [InputControl(name = "note127", displayName = "Note 127 (G9)",   shortDisplayName = "G9",   layout = "MidiNote", offset = 127)]
        public fixed byte notes[128];

        [InputControl(name = "control000", displayName = "Control 0",   shortDisplayName = "CC 0",   layout = "MidiValue", offset = 128)]
        [InputControl(name = "control001", displayName = "Control 1",   shortDisplayName = "CC 1",   layout = "MidiValue", offset = 129)]
        [InputControl(name = "control002", displayName = "Control 2",   shortDisplayName = "CC 2",   layout = "MidiValue", offset = 130)]
        [InputControl(name = "control003", displayName = "Control 3",   shortDisplayName = "CC 3",   layout = "MidiValue", offset = 131)]
        [InputControl(name = "control004", displayName = "Control 4",   shortDisplayName = "CC 4",   layout = "MidiValue", offset = 132)]
        [InputControl(name = "control005", displayName = "Control 5",   shortDisplayName = "CC 5",   layout = "MidiValue", offset = 133)]
        [InputControl(name = "control006", displayName = "Control 6",   shortDisplayName = "CC 6",   layout = "MidiValue", offset = 134)]
        [InputControl(name = "control007", displayName = "Control 7",   shortDisplayName = "CC 7",   layout = "MidiValue", offset = 135)]
        [InputControl(name = "control008", displayName = "Control 8",   shortDisplayName = "CC 8",   layout = "MidiValue", offset = 136)]
        [InputControl(name = "control009", displayName = "Control 9",   shortDisplayName = "CC 9",   layout = "MidiValue", offset = 137)]
        [InputControl(name = "control010", displayName = "Control 10",  shortDisplayName = "CC 10",  layout = "MidiValue", offset = 138)]
        [InputControl(name = "control011", displayName = "Control 11",  shortDisplayName = "CC 11",  layout = "MidiValue", offset = 139)]
        [InputControl(name = "control012", displayName = "Control 12",  shortDisplayName = "CC 12",  layout = "MidiValue", offset = 140)]
        [InputControl(name = "control013", displayName = "Control 13",  shortDisplayName = "CC 13",  layout = "MidiValue", offset = 141)]
        [InputControl(name = "control014", displayName = "Control 14",  shortDisplayName = "CC 14",  layout = "MidiValue", offset = 142)]
        [InputControl(name = "control015", displayName = "Control 15",  shortDisplayName = "CC 15",  layout = "MidiValue", offset = 143)]
        [InputControl(name = "control016", displayName = "Control 16",  shortDisplayName = "CC 16",  layout = "MidiValue", offset = 144)]
        [InputControl(name = "control017", displayName = "Control 17",  shortDisplayName = "CC 17",  layout = "MidiValue", offset = 145)]
        [InputControl(name = "control018", displayName = "Control 18",  shortDisplayName = "CC 18",  layout = "MidiValue", offset = 146)]
        [InputControl(name = "control019", displayName = "Control 19",  shortDisplayName = "CC 19",  layout = "MidiValue", offset = 147)]
        [InputControl(name = "control020", displayName = "Control 20",  shortDisplayName = "CC 20",  layout = "MidiValue", offset = 148)]
        [InputControl(name = "control021", displayName = "Control 21",  shortDisplayName = "CC 21",  layout = "MidiValue", offset = 149)]
        [InputControl(name = "control022", displayName = "Control 22",  shortDisplayName = "CC 22",  layout = "MidiValue", offset = 150)]
        [InputControl(name = "control023", displayName = "Control 23",  shortDisplayName = "CC 23",  layout = "MidiValue", offset = 151)]
        [InputControl(name = "control024", displayName = "Control 24",  shortDisplayName = "CC 24",  layout = "MidiValue", offset = 152)]
        [InputControl(name = "control025", displayName = "Control 25",  shortDisplayName = "CC 25",  layout = "MidiValue", offset = 153)]
        [InputControl(name = "control026", displayName = "Control 26",  shortDisplayName = "CC 26",  layout = "MidiValue", offset = 154)]
        [InputControl(name = "control027", displayName = "Control 27",  shortDisplayName = "CC 27",  layout = "MidiValue", offset = 155)]
        [InputControl(name = "control028", displayName = "Control 28",  shortDisplayName = "CC 28",  layout = "MidiValue", offset = 156)]
        [InputControl(name = "control029", displayName = "Control 29",  shortDisplayName = "CC 29",  layout = "MidiValue", offset = 157)]
        [InputControl(name = "control030", displayName = "Control 30",  shortDisplayName = "CC 30",  layout = "MidiValue", offset = 158)]
        [InputControl(name = "control031", displayName = "Control 31",  shortDisplayName = "CC 31",  layout = "MidiValue", offset = 159)]
        [InputControl(name = "control032", displayName = "Control 32",  shortDisplayName = "CC 32",  layout = "MidiValue", offset = 160)]
        [InputControl(name = "control033", displayName = "Control 33",  shortDisplayName = "CC 33",  layout = "MidiValue", offset = 161)]
        [InputControl(name = "control034", displayName = "Control 34",  shortDisplayName = "CC 34",  layout = "MidiValue", offset = 162)]
        [InputControl(name = "control035", displayName = "Control 35",  shortDisplayName = "CC 35",  layout = "MidiValue", offset = 163)]
        [InputControl(name = "control036", displayName = "Control 36",  shortDisplayName = "CC 36",  layout = "MidiValue", offset = 164)]
        [InputControl(name = "control037", displayName = "Control 37",  shortDisplayName = "CC 37",  layout = "MidiValue", offset = 165)]
        [InputControl(name = "control038", displayName = "Control 38",  shortDisplayName = "CC 38",  layout = "MidiValue", offset = 166)]
        [InputControl(name = "control039", displayName = "Control 39",  shortDisplayName = "CC 39",  layout = "MidiValue", offset = 167)]
        [InputControl(name = "control040", displayName = "Control 40",  shortDisplayName = "CC 40",  layout = "MidiValue", offset = 168)]
        [InputControl(name = "control041", displayName = "Control 41",  shortDisplayName = "CC 41",  layout = "MidiValue", offset = 169)]
        [InputControl(name = "control042", displayName = "Control 42",  shortDisplayName = "CC 42",  layout = "MidiValue", offset = 170)]
        [InputControl(name = "control043", displayName = "Control 43",  shortDisplayName = "CC 43",  layout = "MidiValue", offset = 171)]
        [InputControl(name = "control044", displayName = "Control 44",  shortDisplayName = "CC 44",  layout = "MidiValue", offset = 172)]
        [InputControl(name = "control045", displayName = "Control 45",  shortDisplayName = "CC 45",  layout = "MidiValue", offset = 173)]
        [InputControl(name = "control046", displayName = "Control 46",  shortDisplayName = "CC 46",  layout = "MidiValue", offset = 174)]
        [InputControl(name = "control047", displayName = "Control 47",  shortDisplayName = "CC 47",  layout = "MidiValue", offset = 175)]
        [InputControl(name = "control048", displayName = "Control 48",  shortDisplayName = "CC 48",  layout = "MidiValue", offset = 176)]
        [InputControl(name = "control049", displayName = "Control 49",  shortDisplayName = "CC 49",  layout = "MidiValue", offset = 177)]
        [InputControl(name = "control050", displayName = "Control 50",  shortDisplayName = "CC 50",  layout = "MidiValue", offset = 178)]
        [InputControl(name = "control051", displayName = "Control 51",  shortDisplayName = "CC 51",  layout = "MidiValue", offset = 179)]
        [InputControl(name = "control052", displayName = "Control 52",  shortDisplayName = "CC 52",  layout = "MidiValue", offset = 180)]
        [InputControl(name = "control053", displayName = "Control 53",  shortDisplayName = "CC 53",  layout = "MidiValue", offset = 181)]
        [InputControl(name = "control054", displayName = "Control 54",  shortDisplayName = "CC 54",  layout = "MidiValue", offset = 182)]
        [InputControl(name = "control055", displayName = "Control 55",  shortDisplayName = "CC 55",  layout = "MidiValue", offset = 183)]
        [InputControl(name = "control056", displayName = "Control 56",  shortDisplayName = "CC 56",  layout = "MidiValue", offset = 184)]
        [InputControl(name = "control057", displayName = "Control 57",  shortDisplayName = "CC 57",  layout = "MidiValue", offset = 185)]
        [InputControl(name = "control058", displayName = "Control 58",  shortDisplayName = "CC 58",  layout = "MidiValue", offset = 186)]
        [InputControl(name = "control059", displayName = "Control 59",  shortDisplayName = "CC 59",  layout = "MidiValue", offset = 187)]
        [InputControl(name = "control060", displayName = "Control 60",  shortDisplayName = "CC 60",  layout = "MidiValue", offset = 188)]
        [InputControl(name = "control061", displayName = "Control 61",  shortDisplayName = "CC 61",  layout = "MidiValue", offset = 189)]
        [InputControl(name = "control062", displayName = "Control 62",  shortDisplayName = "CC 62",  layout = "MidiValue", offset = 190)]
        [InputControl(name = "control063", displayName = "Control 63",  shortDisplayName = "CC 63",  layout = "MidiValue", offset = 191)]
        [InputControl(name = "control064", displayName = "Control 64",  shortDisplayName = "CC 64",  layout = "MidiValue", offset = 192)]
        [InputControl(name = "control065", displayName = "Control 65",  shortDisplayName = "CC 65",  layout = "MidiValue", offset = 193)]
        [InputControl(name = "control066", displayName = "Control 66",  shortDisplayName = "CC 66",  layout = "MidiValue", offset = 194)]
        [InputControl(name = "control067", displayName = "Control 67",  shortDisplayName = "CC 67",  layout = "MidiValue", offset = 195)]
        [InputControl(name = "control068", displayName = "Control 68",  shortDisplayName = "CC 68",  layout = "MidiValue", offset = 196)]
        [InputControl(name = "control069", displayName = "Control 69",  shortDisplayName = "CC 69",  layout = "MidiValue", offset = 197)]
        [InputControl(name = "control070", displayName = "Control 70",  shortDisplayName = "CC 70",  layout = "MidiValue", offset = 198)]
        [InputControl(name = "control071", displayName = "Control 71",  shortDisplayName = "CC 71",  layout = "MidiValue", offset = 199)]
        [InputControl(name = "control072", displayName = "Control 72",  shortDisplayName = "CC 72",  layout = "MidiValue", offset = 200)]
        [InputControl(name = "control073", displayName = "Control 73",  shortDisplayName = "CC 73",  layout = "MidiValue", offset = 201)]
        [InputControl(name = "control074", displayName = "Control 74",  shortDisplayName = "CC 74",  layout = "MidiValue", offset = 202)]
        [InputControl(name = "control075", displayName = "Control 75",  shortDisplayName = "CC 75",  layout = "MidiValue", offset = 203)]
        [InputControl(name = "control076", displayName = "Control 76",  shortDisplayName = "CC 76",  layout = "MidiValue", offset = 204)]
        [InputControl(name = "control077", displayName = "Control 77",  shortDisplayName = "CC 77",  layout = "MidiValue", offset = 205)]
        [InputControl(name = "control078", displayName = "Control 78",  shortDisplayName = "CC 78",  layout = "MidiValue", offset = 206)]
        [InputControl(name = "control079", displayName = "Control 79",  shortDisplayName = "CC 79",  layout = "MidiValue", offset = 207)]
        [InputControl(name = "control080", displayName = "Control 80",  shortDisplayName = "CC 80",  layout = "MidiValue", offset = 208)]
        [InputControl(name = "control081", displayName = "Control 81",  shortDisplayName = "CC 81",  layout = "MidiValue", offset = 209)]
        [InputControl(name = "control082", displayName = "Control 82",  shortDisplayName = "CC 82",  layout = "MidiValue", offset = 210)]
        [InputControl(name = "control083", displayName = "Control 83",  shortDisplayName = "CC 83",  layout = "MidiValue", offset = 211)]
        [InputControl(name = "control084", displayName = "Control 84",  shortDisplayName = "CC 84",  layout = "MidiValue", offset = 212)]
        [InputControl(name = "control085", displayName = "Control 85",  shortDisplayName = "CC 85",  layout = "MidiValue", offset = 213)]
        [InputControl(name = "control086", displayName = "Control 86",  shortDisplayName = "CC 86",  layout = "MidiValue", offset = 214)]
        [InputControl(name = "control087", displayName = "Control 87",  shortDisplayName = "CC 87",  layout = "MidiValue", offset = 215)]
        [InputControl(name = "control088", displayName = "Control 88",  shortDisplayName = "CC 88",  layout = "MidiValue", offset = 216)]
        [InputControl(name = "control089", displayName = "Control 89",  shortDisplayName = "CC 89",  layout = "MidiValue", offset = 217)]
        [InputControl(name = "control090", displayName = "Control 90",  shortDisplayName = "CC 90",  layout = "MidiValue", offset = 218)]
        [InputControl(name = "control091", displayName = "Control 91",  shortDisplayName = "CC 91",  layout = "MidiValue", offset = 219)]
        [InputControl(name = "control092", displayName = "Control 92",  shortDisplayName = "CC 92",  layout = "MidiValue", offset = 220)]
        [InputControl(name = "control093", displayName = "Control 93",  shortDisplayName = "CC 93",  layout = "MidiValue", offset = 221)]
        [InputControl(name = "control094", displayName = "Control 94",  shortDisplayName = "CC 94",  layout = "MidiValue", offset = 222)]
        [InputControl(name = "control095", displayName = "Control 95",  shortDisplayName = "CC 95",  layout = "MidiValue", offset = 223)]
        [InputControl(name = "control096", displayName = "Control 96",  shortDisplayName = "CC 96",  layout = "MidiValue", offset = 224)]
        [InputControl(name = "control097", displayName = "Control 97",  shortDisplayName = "CC 97",  layout = "MidiValue", offset = 225)]
        [InputControl(name = "control098", displayName = "Control 98",  shortDisplayName = "CC 98",  layout = "MidiValue", offset = 226)]
        [InputControl(name = "control099", displayName = "Control 99",  shortDisplayName = "CC 99",  layout = "MidiValue", offset = 227)]
        [InputControl(name = "control100", displayName = "Control 100", shortDisplayName = "CC 100", layout = "MidiValue", offset = 228)]
        [InputControl(name = "control101", displayName = "Control 101", shortDisplayName = "CC 101", layout = "MidiValue", offset = 229)]
        [InputControl(name = "control102", displayName = "Control 102", shortDisplayName = "CC 102", layout = "MidiValue", offset = 230)]
        [InputControl(name = "control103", displayName = "Control 103", shortDisplayName = "CC 103", layout = "MidiValue", offset = 231)]
        [InputControl(name = "control104", displayName = "Control 104", shortDisplayName = "CC 104", layout = "MidiValue", offset = 232)]
        [InputControl(name = "control105", displayName = "Control 105", shortDisplayName = "CC 105", layout = "MidiValue", offset = 233)]
        [InputControl(name = "control106", displayName = "Control 106", shortDisplayName = "CC 106", layout = "MidiValue", offset = 234)]
        [InputControl(name = "control107", displayName = "Control 107", shortDisplayName = "CC 107", layout = "MidiValue", offset = 235)]
        [InputControl(name = "control108", displayName = "Control 108", shortDisplayName = "CC 108", layout = "MidiValue", offset = 236)]
        [InputControl(name = "control109", displayName = "Control 109", shortDisplayName = "CC 109", layout = "MidiValue", offset = 237)]
        [InputControl(name = "control110", displayName = "Control 110", shortDisplayName = "CC 110", layout = "MidiValue", offset = 238)]
        [InputControl(name = "control111", displayName = "Control 111", shortDisplayName = "CC 111", layout = "MidiValue", offset = 239)]
        [InputControl(name = "control112", displayName = "Control 112", shortDisplayName = "CC 112", layout = "MidiValue", offset = 240)]
        [InputControl(name = "control113", displayName = "Control 113", shortDisplayName = "CC 113", layout = "MidiValue", offset = 241)]
        [InputControl(name = "control114", displayName = "Control 114", shortDisplayName = "CC 114", layout = "MidiValue", offset = 242)]
        [InputControl(name = "control115", displayName = "Control 115", shortDisplayName = "CC 115", layout = "MidiValue", offset = 243)]
        [InputControl(name = "control116", displayName = "Control 116", shortDisplayName = "CC 116", layout = "MidiValue", offset = 244)]
        [InputControl(name = "control117", displayName = "Control 117", shortDisplayName = "CC 117", layout = "MidiValue", offset = 245)]
        [InputControl(name = "control118", displayName = "Control 118", shortDisplayName = "CC 118", layout = "MidiValue", offset = 246)]
        [InputControl(name = "control119", displayName = "Control 119", shortDisplayName = "CC 119", layout = "MidiValue", offset = 247)]
        [InputControl(name = "control120", displayName = "Control 120", shortDisplayName = "CC 120", layout = "MidiValue", offset = 248)]
        [InputControl(name = "control121", displayName = "Control 121", shortDisplayName = "CC 121", layout = "MidiValue", offset = 249)]
        [InputControl(name = "control122", displayName = "Control 122", shortDisplayName = "CC 122", layout = "MidiValue", offset = 250)]
        [InputControl(name = "control123", displayName = "Control 123", shortDisplayName = "CC 123", layout = "MidiValue", offset = 251)]
        [InputControl(name = "control124", displayName = "Control 124", shortDisplayName = "CC 124", layout = "MidiValue", offset = 252)]
        [InputControl(name = "control125", displayName = "Control 125", shortDisplayName = "CC 125", layout = "MidiValue", offset = 253)]
        [InputControl(name = "control126", displayName = "Control 126", shortDisplayName = "CC 126", layout = "MidiValue", offset = 254)]
        [InputControl(name = "control127", displayName = "Control 127", shortDisplayName = "CC 127", layout = "MidiValue", offset = 255)]
        public fixed byte controls[128];

        // Format/size must be specified directly since the input system overrides it with the type of the field
        // [InputControl(name = "pitchBend", displayName = "Pitch Bend", shortDisplayName = "Pitch", layout = "MidiPitch", defaultState = 8192)]
        [InputControl(name = "pitchBend", displayName = "Pitch Bend", shortDisplayName = "Pitch", layout = "MidiPitch", format = "BIT", sizeInBits = 14, defaultState = 8192)]
        public ushort pitchBend;
    }
}
