name: Acquire activation file

on:
  workflow_dispatch: {}

env:
  unityVersion: "6000.3.5f2"
  unityVersionHash: "3fa8bc678cb0"

jobs:
  linux-activation:
    name: Linux - Request activation file
    runs-on: ubuntu-22.04
    timeout-minutes: 90
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get -q update
          sudo apt-get -q install -y --no-install-recommends ca-certificates libasound2 libc6-dev libcap2 libglu1 libgtk-3-0 libncurses5 libnotify4 libnss3 libxtst6 libxss1 cpio lsb-release xvfb xz-utils
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*

      - name: Download Unity Editor
        run: |
          mkdir "${{ runner.temp }}/UnityInstall"
          curl -L -o "${{ runner.temp }}/UnityInstall/UnitySetup-Editor.tar.xz" \
            "https://download.unity3d.com/download_unity/${{ env.unityVersionHash }}/LinuxEditorInstaller/Unity-${{ env.unityVersion }}.tar.xz"

      - name: Install Unity Editor
        run: |
          mkdir "${{ runner.temp }}/Unity"
          tar -xf "${{ runner.temp }}/UnityInstall/UnitySetup-Editor.tar.xz" -C "${{ runner.temp }}/Unity"

      - name: Request manual activation file
        run: ${{ runner.temp }}/Unity/Editor/Unity -quit -batchmode -createManualActivationFile -logfile -

      - name: Upload activation file
        uses: actions/upload-artifact@v4
        with:
          name: Unity-${{ env.unityVersion }}-Linux-activation
          path: "*.alf"

  windows-activation:
    name: Windows - Request activation file
    runs-on: windows-2025
    timeout-minutes: 90
    steps:
      - name: Download Unity Editor
        run: |
          mkdir ${{ runner.temp }}\UnityInstall
          curl -L -o "${{ runner.temp }}\UnityInstall\UnitySetup64-${{ env.unityVersion }}.exe" `
            "https://download.unity3d.com/download_unity/${{ env.unityVersionHash }}/Windows64EditorInstaller/UnitySetup64-${{ env.unityVersion }}.exe"

      - name: Install Unity
        run: |
          $args = "/S /D=${{ runner.temp }}\\Unity"
          Start-Process "${{ runner.temp }}\UnityInstall\UnitySetup64-${{ env.unityVersion }}.exe" -ArgumentList $args -Wait -NoNewWindow

      - name: Request manual activation file
        run: |
          & "${{ runner.temp }}/Unity/Editor/Unity.exe" -quit -batchmode -createManualActivationFile -logfile | Out-Host

      - name: Upload activation file
        uses: actions/upload-artifact@v4
        with:
          name: Unity-${{ env.unityVersion }}-Windows-activation
          path: "*.alf"
