name: Builds - MacOS

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  macBuilder:
    name: ${{ matrix.targetPlatform }} on ${{ matrix.unityVersion }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        # projectPath:
        #   - test-project
        unityVersion:
          - 2021.3.21f1
        targetPlatform:
          - StandaloneOSX

    steps:
      ###########################
      #         Checkout        #
      ###########################
      - name: "[Pre-install] Pull project"
        uses: actions/checkout@v3
        with:
          lfs: true

      ###########################
      #          Cache          #
      ###########################
      - name: "[Pre-install] Restore 'library' cache"
        uses: actions/cache@v3
        with:
          path: Library
          key: YARG-Library-macos-${{ matrix.targetPlatform }}
          restore-keys: |
            YARG-Library-macos-
            YARG-Library-

      ###########################
      #    Install Libraries    #
      ###########################
      - name: "[Install Libraries] Setup Python 3.10"
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: "[Install Libraries] Install 'requests' package on Python"
        run: pip install requests

      - name: "[Install Libraries] Install libraries"
        run: python InstallLibraries/install.py
        
      ###########################
      #    Restore  Packages    #
      ###########################

      # next-line is TEMPORARY
      - name: "[Restore Packages] Check dotnet"
        run: dotnet --info

      - name: "[Restore Packages] Install NuGetForUnity.Cli"
        run: dotnet tool install --global NuGetForUnity.Cli

      - name: "[Restore Packages] Restoring"
        run: dotnet nugetforunity restore

      ###########################
      #          Build          #
      ###########################
      - name: "[Build] Run Builder"
        uses: game-ci/unity-builder@main
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          # projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          cacheUnityInstallationOnMac: true

      ###########################
      #          Upload         #
      ###########################
      - name: "[Post-build] Upload build to artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: Build MacOS
          path: build/StandaloneOSX
          retention-days: 14