name: Fix macOS permissions on latest released build

on:
  workflow_dispatch:
    inputs:
      createZip:
        description: "Create .zip file"
        default: true
        type: boolean
      createDmg:
        description: "Create .dmg file"
        default: true
        type: boolean

jobs:
  fixMacBuild:
    name: Fixing Mac permissions for ${{ github.ref }}
    runs-on: macos-latest

    steps: 
      - name: Get Latest Release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: YARC-Official
          repo: YARG
          token: ${{ github.token }}

      - name: Unzip release
        run: find . -name *.zip -print -exec unzip {} \;

      - name: Check contents (temporary)
        run: ls

      - name: Fix file attributes
        run: |
          if ! type "xattr" > /dev/null; then
            echo "xattr does not exist"
          else
            find . -name *.app -print -exec xattr -cr {} \;
          fi

      - name: Fix permissions
        run: find . -name *.app -print -exec chmod +x {}/Contents/MacOS/YARG \;

      - name: Create Packages folder
        run: mkdir Packages

      - if: ${{ inputs.createZip == true }}
        name: "Creating .zip"
        run: find . -name *.app -print -exec ditto -c -k --keepParent {} Packages \; 


      - name: "Creating .dmg"
        if: ${{ inputs.createDmg == true }}
        continue-on-error: true
        run: >
          echo "- Installing create-dmg" &&
          brew install graphicsmagick imagemagick &&
          npm install --global create-dmg &&
          echo "- Creating DMG" &&
          find . -name *.app -print -exec create-dmg --dmg-title=YARG {} Packages \; 


      - name: "Upload pacakges to artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: Packages
          path: Packages